# The singles
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             adderCompton
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             adder

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             readout
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/readout/setDepth                   1

#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert         clustering
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/clustering/setAcceptedDistance 10 mm
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/clustering/setRejectionMultipleClusters        0

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             energyResolution
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyResolution/fwhm              0.10
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             energyFraming
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMin               411. keV
/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/energyFraming/setMax               611. keV

#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/insert                             timeResolution
#/gate/digitizerMgr/crystal/SinglesDigitizer/Singles/timeResolution/fwhm                4.7 ns

# Coincidence sorter
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection               Singles_crystal
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow                        10 ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy                  takeWinnerOfGoods

/gate/digitizerMgr/name                                                            delay
/gate/digitizerMgr/insert                                                          CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection                      Singles_crystal
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow                               10 ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset                               500  ns
#/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy                         takeWinnerOfGoods
