# The singles
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             adderCompton
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             adder

/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             readout
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/readout/setDepth                   1

/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             energyResolution
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/energyResolution/fwhm              0.07
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/energyResolution/energyOfReference 511. keV

/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             energyFraming
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/energyFraming/setMin               411. keV
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/energyFraming/setMax               611. keV

/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             timeResolution
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/timeResolution/fwhm                4.7 ns

/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/insert                             spatialResolution
/gate/digitizerMgr/CsI/SinglesDigitizer/Singles/spatialResolution/fwhm             1.0 mm

# Coincidence sorter
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setInputCollection               Singles_CsI
/gate/digitizerMgr/CoincidenceSorter/Coincidences/setWindow                        10 ns
/gate/digitizerMgr/CoincidenceSorter/Coincidences/MultiplesPolicy                  takeWinnerOfGoods

/gate/digitizerMgr/name                                                            delay
/gate/digitizerMgr/insert                                                          CoincidenceSorter
/gate/digitizerMgr/CoincidenceSorter/delay/setInputCollection                      Singles_CsI
/gate/digitizerMgr/CoincidenceSorter/delay/setWindow                               10 ns
/gate/digitizerMgr/CoincidenceSorter/delay/setOffset                               5 us
/gate/digitizerMgr/CoincidenceSorter/delay/MultiplesPolicy                         takeWinnerOfGoods
