
/gate/source/addSource normalization_source
/gate/source/normalization_source/setActivity 100000. becquerel

/gate/source/normalization_source/gps/particle gamma
/gate/source/normalization_source/gps/ene/mono 511. keV
/gate/source/normalization_source/gps/type Volume
/gate/source/normalization_source/gps/shape Cylinder
/gate/source/normalization_source/gps/radius .5 mm
/gate/source/normalization_source/gps/halfz 34.0 cm
/gate/source/normalization_source/gps/angtype iso
/gate/source/normalization_source/gps/centre 0. 0 0. cm
/gate/source/normalization_source/setType        backtoback


/gate/source/list

